services:
  db:
    image: postgres:18
    environment:
      'POSTGRES_DB': '${DATABASE}'
      'POSTGRES_PASSWORD': '${PASSWORD}'
      'POSTGRES_USER': '${USERNAME}'
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
  
  hallifyapi:
    image: hallifyapi
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: HallifyApi/Dockerfile
    environment:
      'ConnectionStrings__DefaultConnection': 'Host=db;Database=${DATABASE};Username=${USERNAME};Password=${PASSWORD}'

volumes:
  pgdata: